library(twitteR)
library(sentiment)
library(plyr)
library(ggplot2)
library(wordcloud)
library(RColorBrewer)
setup_twitter_oauth('45NnOSZTY2LzswH5FIXyz7QJn','nScg6Ea3ojWVHJAQf1BE93MnKhq0MT1Eq2rqfDXuw1Bt1CyNaR', access_token=NULL, access_secret=NULL)
some_tweets = searchTwitter("Trump", n=1500, lang="en")
some_txt = sapply(some_tweets, function(x) x$getText())
some_txt = gsub("(RT|via)((?:\\b\\W*@\\w+)+)", "", some_txt)
some_txt = gsub("@\\w+", "", some_txt)
some_txt = gsub("[[:punct:]]", "", some_txt)
some_txt = gsub("[[:digit:]]", "", some_txt)
some_txt = gsub("http\\w+", "", some_txt)
some_txt = gsub("[ \t]{2,}", "", some_txt)
some_txt = gsub("^\\s+|\\s+$", "", some_txt)
